### ISSUE TITLE
There is an error, when I push without a tag

### ISSUE THREAD

**Issue by L-Super** [devops-actions/action-get-tag#66]
I have set `default` value, but I still get an error message
```
Warning: Unexpected input(s) 'default', valid inputs are ['strip_v']
Run devops-actions/action-get-tag@v1.0.1
  with:
    default: v0.0.0
    strip_v: false
  env:
    build_type: Release
Error: Not a tag ref (refs/heads/main)
```

**Comment by rajbos** [comment]
@L-Super : the default input was not available yet in version v1.0.1, you'll need to use `devops-actions/action-get-tag@v1.0.2` to be able to do so. I see I had the old version number in the README, which is now updated with #67.

**Comment by L-Super** [comment]
Most of the time, commits do not have tags, and this will cause an error, but I hope the process can continue. Is there a way to achieve this without setting a default version?

**Comment by rajbos** [comment]
I'd add an 'if' to the step and skip if this is not a tag commit?

**Comment by L-Super** [comment]
> I'd add an 'if' to the step and skip if this is not a tag commit?

Here's a solution. I'm currently manually adding `if` to determine if there is a tag

**Comment by rajbos** [comment]
@L-Super , can you share the `if` statement here for future reference?

**Comment by L-Super** [comment]
> @L-Super , can you share the `if` statement here for future reference? 

```
- name: Get tag
        uses: devops-actions/action-get-tag@v1.0.1
        if: startsWith(github.event.ref, 'refs/tags/')
        id: tag
```
